### ISSUE TITLE
Add glasgow crit reverse?

### ISSUE THREAD

**Issue by jessicah** [Zenmaster28/Zenmaster-s4z-mods#4]
Will you be adding the new course to your mod? I looked at doing myself, but I don't know how to generate the manifest portion.

**Comment by Zenmaster28** [comment]
Yes, I've asked the Sauce dev for an updated routes file.  Once I get that, I will release an update to include it.

**Comment by Zenmaster28** [comment]
1.2.4 release includes the Glasgow crit reverse course
