### ISSUE TITLE
New Watopia routes?

### ISSUE THREAD

**Issue by jessicah** [Zenmaster28/Zenmaster-s4z-mods#5]
Will you also be adding the new Watopia routes? It seems like there's been no public updates of s4z in quite a while. Would be nice if I could do these myself, but I don't have access to his Discord to ask how it's done.

**Comment by Zenmaster28** [comment]
If you are a Patreon supporter of Sauce you can join the discord for Sauce.  There was just (a few hours ago) an alpha update to Sauce that has the new routes but I've just n9ticed my mod has a bug that I will have to fix to.

**Comment by Zenmaster28** [comment]
New Watopia routes will display properly now if you use the 1.3.3 release AND update to the alpha 1.1.6 release of Sauce
